server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gongcaedan-auth
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_URL}
      port: 6379

jwt:
  token:
    secret: ${JWT_SECRET_BASE64}
  access-token-expiration: 3600000      # 1시간
  refresh-token-expiration: 604800000   # 7일

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    prefer-ip-address: false              # IP 기반 등록 비활성화 (핵심!)
    hostname: gongcaedan-auth             # Kubernetes Service 이름
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port: ${server.port}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info